In [38]:
import tensorflow as tf

In [39]:
tf_con = tf.constant([[1.0, 2.0],[3.0, 4.0]])

In [40]:
tf_con

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [41]:
tf_con.shape

TensorShape([2, 2])

In [42]:
tf_con[:,:1]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [3.]], dtype=float32)>

In [43]:
import pandas as pd

In [44]:
pd1 = pd.DataFrame([[1,2],[3,4]])

In [45]:
pd1.iloc[1]

0    3
1    4
Name: 1, dtype: int64

In [46]:
pd1.loc[1]

0    3
1    4
Name: 1, dtype: int64

In [47]:
pd1[1]

0    2
1    4
Name: 1, dtype: int64

In [48]:
pd1.values

array([[1, 2],
       [3, 4]])

In [49]:
type(pd1.values)

numpy.ndarray

In [50]:
t = tf_con

In [51]:
t

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [52]:
t + 2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [5., 6.]], dtype=float32)>

In [53]:
print(t)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [54]:
t[:,:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [55]:
t.shape

TensorShape([2, 2])

In [56]:
t[1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

In [57]:
t+1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [58]:
t+2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [5., 6.]], dtype=float32)>

In [59]:
t.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [60]:
tf.__version__

'2.14.1'

In [61]:
tf.square(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  4.],
       [ 9., 16.]], dtype=float32)>

In [62]:
t.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [64]:
tf.constant(2.0) + tf.cast(1,tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [66]:
v = tf.Variable([[1,2,3],[4.0, 5.0, 6.0]]) #只能有一种类型

In [67]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [68]:
v.assign(v*2)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [69]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [70]:
t

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [71]:
t+2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3., 4.],
       [5., 6.]], dtype=float32)>

In [72]:
t

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [73]:
v * 2

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 4.,  8., 12.],
       [16., 20., 24.]], dtype=float32)>

In [74]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [77]:
type(t)

tensorflow.python.framework.ops.EagerTensor

In [78]:
print(1)

1


In [79]:
print(1)

1
